baseurl = "https://cyrusn.github.io"
DefaultContentLanguage = "en"
title = "CyrusN"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
disqusShortname = "cyrusngithubio"
#googleAnalytics = "XXX"

[blackfriday]
  # angledQuotes = true
  # fractions = false
  # plainIDAnchors = true
  extensions = ["hardLineBreak"]

[Params]
  subtitle = "My Notes"
  logo = "img/avatar.png"
  favicon = "favicon.ico"
  dateFormat = "2006-01-02"
  commit = false
  rss = false
  comments = true
  search = true
  showHint = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "CyrusN"
  email = "cyrusncy@gmail.com"
  github = "cyrusn"
  facebook = "cyrusncy"
  twitter = "cyrusncy"
  # googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  # reddit = "username"
  # linkedin = "username"
  # xing = "username"
  # stackoverflow = "users/XXXXXXX/username"
  # snapchat = "username"
  # instagram = "username"
  # youtube = "user/username" # or channel/channelname
  # soundcloud = "username"
  # spotify = "username"
  # bandcamp = "username"
  # itchio = "username"

[[menu.main]]
    name = "Home"
    identifier = "home"
    url = ""
    weight = 1

# [[menu.main]]
#     name = "Post"
#     identifier = "post"
#     url = "/post/"
#     weight = 2

[[menu.main]]
    name = "Note"
    identifier = "note"
    url = "/note/"
    weight = 3

[[menu.main]]
    name = "Project"
    identifier = "project"
    url = "/project/"
    weight = 4

[[menu.main]]
    name = "Slide"
    identifier = "slide"
    url = "/slide/"
    weight = 5

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 10

[[menu.main]]
name = "About"
url = "/page/about/"
weight = 20

[outputs]
home = [ "HTML", "RSS", "JSON"]
